name: Deployment of python application


on:
  pull_request:
    branches:
    - main
    - dev
    - prod



jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Print simple statement
        run : echo "A mail has been sent to manager!"

